### ISSUE TITLE
Playtube

### ISSUE THREAD

**Issue by olliedarou** [jsergio123/script.module.resolveurl#457]
Playtube does not work error 403
Please fix it

**Comment by olliedarou** [comment]
here that works

https://github.com/vb6rocod/utils/blob/master/servere/tear_js.html

**Comment by Gujal00** [comment]
Fixed in https://github.com/jsergio123/script.module.resolveurl/commit/7494f858602bc92be674f57a1741416cfdcc22be

**Comment by caperucitaferoz** [comment]
I am testing this server and sometimes the **same link** works and other times it returns an error: **expected string or bytes-like object**

```
2021-05-25 18:51:37.974 T:4872    ERROR <general>:   File "C:\Users\caperucita\Desktop\Kodi_19\portable_data\addons\script.module.resolveurl\lib\resolveurl\__init__.py", line 128, in resolve   
2021-05-25 18:51:37.975 T:4872    ERROR <general>: return source.resolve()
2021-05-25 18:51:37.975 T:4872    ERROR <general>:   File "C:\Users\caperucita\Desktop\Kodi_19\portable_data\addons\script.module.resolveurl\lib\resolveurl\hmf.py", line 187, in resolve   
2021-05-25 18:51:37.977 T:4872    ERROR <general>: stream_url = resolver.get_media_url(self._host, self._media_id)
2021-05-25 18:51:37.977 T:4872    ERROR <general>:   File "C:\Users\caperucita\Desktop\Kodi_19\portable_data\addons\script.module.resolveurl\lib\resolveurl\plugins\playtube.py", line 46, in get_media_url   
2021-05-25 18:51:37.978 T:4872    ERROR <general>: source = helpers.tear_decode(resp.get('file'), resp.get('seed'))
2021-05-25 18:51:37.978 T:4872    ERROR <general>:   File "C:\Users\caperucita\Desktop\Kodi_19\portable_data\addons\script.module.resolveurl\lib\resolveurl\plugins\lib\helpers.py", line 571, in tear_decode
2021-05-25 18:51:37.980 T:4872    ERROR <general>: data_seed = re.sub('[012567]', replacer, data_seed)
2021-05-25 18:51:37.981 T:4872    ERROR <general>:   File "C:\Users\caperucita\Desktop\Kodi_19\system\python\Lib\re.py", line 210, in sub
2021-05-25 18:51:37.983 T:4872    ERROR <general>: return _compile(pattern, flags).sub(repl, string, count)
2021-05-25 18:51:37.983 T:4872    ERROR <general>: TypeError
2021-05-25 18:51:37.984 T:4872    ERROR <general>: : 
2021-05-25 18:51:37.984 T:4872    ERROR <general>: expected string or bytes-like object
```

**Comment by Gujal00** [comment]
Sometimes the server is slow and doesn't return the response in time, may be it happens then
I will add a check in the next release to see if there was a proper response before continuing and fail gracefully if no response

**Comment by caperucitaferoz** [comment]
With the new [commit ](https://github.com/jsergio123/script.module.resolveurl/commit/dd7df92120b33eb6a8a93edec9f6a720447c9360) the error no longer occurs, but there will continue to be cases in which it is not resolved correctly. 
I was wondering if a replay of the [call ](https://github.com/jsergio123/script.module.resolveurl/blob/dd7df92120b33eb6a8a93edec9f6a720447c9360/lib/resolveurl/plugins/playtube.py#L44) could get a link resolved?

**Comment by Gujal00** [comment]
@caperucitaferoz 
I am unable to simulate the error with the test embeds that I have. Do you have any embeds that behave this way?

Worst case scenario, the user needs to click on the link again, at least fails gracefully now without the dreaded beep

**Comment by caperucitaferoz** [comment]
in protonmail..
